name: MathChallengePlugin
version: '1.0.0'
main: ru.doz.mathchallengeplugin.MathChallengePlugin
api-version: '1.21'

commands:
  mathchallenge:
    description: "Начать математический вызов"
    aliases:
      - math
